services:
  redis:
    image: redis:7.4-alpine
    container_name: suppy-inventory-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped
